Add capi-pcidss-v2 chart
rbkmoney/helmsdeep pull request #19
Opened 2020-08-21 07:17 UTC by 0x42

2020-08-21 08:24 UTC, kehitt commented on services/capi-pcidss-v2/values.yaml
> +  path: /v2
```suggestion
  host: api.rbk.dev
  path: /v2/processing/payment-resources
```

2020-08-26 18:52 UTC, ciiol reviewed
Я бы еще предложил добавить изменения аналогичные rbkmoney/helmsdeep#22

2020-08-27 13:44 UTC, ciiol requested changes

2020-08-27 13:44 UTC, ciiol commented on services/capi-pcidss-v2/templates/deployment.yaml
> +    {{- end }}
А зачем сюда добавлять? Это же не описание пода

2020-08-28 11:25 UTC, ciiol approved these changes

2020-08-28 11:28 UTC, merged